
class EXCEPTION_TOKEN {
  static const String LOGIN_USERNAME_INCORRECT = 'LOGIN_USERNAME_INCORRECT';
  static const String LOGIN_PASSWORD_INCORRECT = 'LOGIN_PASSWORD_INCORRECT';
  static const String REGISTER_EXISTED_USERNAME = 'REGISTER_EXISTED_USERNAME';
  static const String REGISTER_NULL_USERNAME = 'REGISTER_NULL_USERNAME';
}